[package]
name = "vulkan-triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = { git = "https://github.com/PistonDevelopers/glfw-rs" }

[build-dependencies]
bindgen = "0.60.1"
